# Generated by Django 5.1.7 on 2025-03-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
    ]

# from django.db import migrations,models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('trainee', 'last_migration_file_name'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='trainee',
#             name='course',
#             field=models.ForeignKey(
#                 to='course.Course', on_delete=models.CASCADE, related_name='trainees', null=True
#             ),
#         ),
#         migrations.AddField(
#             model_name='trainee',
#             name='mentor',
#             field=models.ForeignKey(
#                 'trainee.Trainee', on_delete=models.SET_NULL, null=True, blank=True, related_name="mentees"
#             ),
#         ),
#     ]
